#if !defined(AFX_GPIBNOTIFY_H__A7367990_B935_11D8_9B27_00801E0328BA__INCLUDED_)
#define AFX_GPIBNOTIFY_H__A7367990_B935_11D8_9B27_00801E0328BA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CGpibNotify wrapper class

class CGpibNotify : public CWnd
{
protected:
	DECLARE_DYNCREATE(CGpibNotify)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xf2edd384, 0xca84, 0x11cf, { 0xa5, 0x1e, 0x0, 0x20, 0xaf, 0x68, 0x45, 0xf6 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetSetupMask();
	void SetSetupMask(long);

// Operations
public:
	long SetupNotify(long Ud, const VARIANT& SetupMask);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_GPIBNOTIFY_H__A7367990_B935_11D8_9B27_00801E0328BA__INCLUDED_)
