// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gpibnotify.h"

/////////////////////////////////////////////////////////////////////////////
// CGpibNotify

IMPLEMENT_DYNCREATE(CGpibNotify, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGpibNotify properties

long CGpibNotify::GetSetupMask()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CGpibNotify::SetSetupMask(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGpibNotify operations

long CGpibNotify::SetupNotify(long Ud, const VARIANT& SetupMask)
{
	long result;
	static BYTE parms[] =
		VTS_I4 VTS_VARIANT;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_I4, (void*)&result, parms,
		Ud, &SetupMask);
	return result;
}

void CGpibNotify::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
