//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Calorimetro_2011.rc
//
#define IDCHANGE                        3
#define IDM_LOWLVLCNF                   101
#define IDD_PULSER                      103
#define IDD_TCONTROL                    104
#define IDD_CONTROLPANEL                105
#define IDD_PLOTS                       106
#define IDD_DURATION                    107
#define IDD_DOFIT                       108
#define IDD_EXP1                        109
#define IDD_EXP2                        110
#define IDD_LIN                         111
#define IDD_EASTEREGG                   117
#define IDR_MAINFRAME                   128
#define IDB_CALOR                       129
#define IDD_BOLREADER_SETTINGS          129
#define IDI_READINGS                    130
#define IDI_ICONMSG                     131
#define IDD_GEREADER_SETTING            131
#define IDB_READINGS                    132
#define IDD_CURRGEN_SETTINGS            133
#define IDB_SPLASH                      134
#define IDD_TCONTROL_SETTINGS           135
#define IDD_LAKESHORE_370               137
#define IDD_SPLASH                      140
#define IDD_READBOLCALFILE              141
#define IDD_PROCESSING                  143
#define IDD_BOL_READER                  236
#define IDD_GE_READER                   238
#define IDD_CURRENT_GENERATOR           240
#define IDC_MODEL                       1000
#define IDC_MSFLEXGRID                  1000
#define IDD_PARDLG                      1000
#define IDC_DONE                        1000
#define IDC_SETP                        1000
#define IDD_MINUIT_DIALOG               1001
#define IDC_FIT                         1001
#define IDC_ADDRESS                     1002
#define IDC_CONFIGURE                   1002
#define IDD_APIEZON_SETTINGS            1002
#define IDC_GOCOM                       1003
#define IDC_BITMAP                      1005
#define IDC_COMMAND                     1008
#define IDC_OVERWRITE                   1009
#define IDC_STARTSTOP                   1009
#define ID_MERGE                        1010
#define IDC_XMIN                        1011
#define IDC_SAVE                        1011
#define IDC_XMAX                        1012
#define IDC_PROCESS_DATA                1012
#define IDC_FILENAME                    1013
#define IDC_YMIN                        1013
#define IDC_YMAX                        1014
#define IDC_CHANGET1                    1018
#define IDC_LOGX                        1019
#define IDC_CHANGEC1                    1019
#define IDC_LOGY                        1020
#define IDC_CHANGEC2                    1020
#define IDC_CHANGET2                    1021
#define IDC_CHANGEC3                    1022
#define IDC_CHANGET3                    1023
#define IDC_SCALE                       1023
#define IDC_CHANGEC4                    1024
#define IDC_DIGITS                      1024
#define IDC_CHANGET4                    1025
#define IDC_PLC                         1025
#define IDC_FILET1                      1026
#define IDC_AZERO                       1026
#define IDC_RANGE                       1027
#define IDC_FILET2                      1027
#define IDC_FILET3                      1028
#define IDC_CURRENT                     1028
#define IDC_CURRENTS                    1029
#define IDC_FILET4                      1029
#define IDC_WIDTH                       1030
#define IDC_FILEC1                      1030
#define IDC_SENSORCURRENT               1031
#define IDC_DELAY                       1031
#define IDC_H1                          1031
#define IDC_RESISTANCE                  1032
#define IDC_FILEC2                      1032
#define IDC_FILE_APIEZON                1032
#define IDC_FILEC3                      1033
#define IDC_CHANGE                      1033
#define IDC_FILEC4                      1034
#define IDC_HEATER                      1036
#define IDC_EDIT_P                      1037
#define IDC_EDIT_D                      1038
#define IDC_EDIT_I                      1039
#define IDC_SENSCUR                     1040
#define IDC_GEREADER                    1041
#define IDC_PLOTS                       1052
#define IDC_PLOTACTIVE                  1055
#define IDC_AUTORANGEX                  1056
#define IDC_AUTORANGEY                  1060
#define IDC_DURATION                    1060
#define IDC_FILEPAR                     1061
#define IDC_RFILI1                      1061
#define IDC_RTOT1                       1062
#define IDC_RFILI2                      1063
#define IDC_RTOT2                       1064
#define IDC_MASS_1                      1065
#define IDC_H2                          1067
#define IDC_APIEZON_1                   1068
#define IDC_Y0                          1069
#define IDC_MASS_2                      1069
#define IDC_Y1                          1070
#define IDC_APIEZON_2                   1070
#define IDC_F                           1071
#define IDC_RFILI3                      1071
#define IDC_T0                          1072
#define IDC_RTOT3                       1072
#define IDC_Y2                          1073
#define IDC_H3                          1073
#define IDC_F2                          1074
#define IDC_MASS_3                      1074
#define IDC_EXP1                        1074
#define IDC_APIEZON_3                   1075
#define IDC_RFILI4                      1076
#define IDC_RTOT4                       1077
#define IDC_EXP2                        1077
#define IDC_H4                          1078
#define IDC_LIN                         1078
#define IDC_MASS_4                      1079
#define IDC_GER                         1079
#define IDC_APIEZON_4                   1080
#define IDC_BOL                         1080
#define IDC_CONVERGED                   1082
#define IDC_OVERFLOW                    1084
#define IDC_CHI2                        1085
#define IDC_A                           1086
#define IDC_B                           1087
#define IDC_F1                          1088
#define IDC_STARTSCTRL                  1149

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
